defaults:
  - common
  - _self_

name: skimo

phase: pretrain

# SkiMo
n_skill: 10
skill_horizon: 10
skill_dim: 10

# Pretraining
pretrain:
  max_global_step: 200000
  train_iter: 5
  log_every: 10
  evaluate_every: 100
  ckpt_every: 1000
  batch_size: 256
  split: {train: 0.99, val: 0.01, test: 0.0}
  n_vis: 1
  data_path: null

# Training
joint_training: true
freeze_model: false
sac: false
sample_last_more: true

use_prior: false
prior_reg_critic: false
fixed_alpha: null
alpha_init: 1
alpha_lr: 3e-4
target_divergence: 1
alpha_step: 25000

max_global_step: 2000000
warm_up_step: 5000
train_every: 500
train_iter: 10
log_every: 500
evaluate_every: 5000
ckpt_every: 50000
pretrain_ckpt_path: null

batch_size: 64
rl_discount: 0.99
ob_norm: false

buffer_size: 1000000
reward_scale: 1.0

target_update_freq: 2
target_update_tau: 0.99

# Loss
joint_lr: 1e-3
model_lr: 1e-3
actor_lr: 1e-3
grad_clip: 100.0
scalars:
  hl_actor: 1
  hl_model: 1
  hl_reward: 0.5
  hl_value: 0.1
  ll_actor: 1
  consistency: 2
  rho: 0.5
  encoder_kl: 1e-4
  hl_prior: 1
max_divergence: 100

# CEM
use_cem: true
cem_iter: 6
num_elites: 64
num_sample_traj: 512
num_policy_traj: 25
cem_momentum: 0.1
cem_temperature: 0.5
max_std: 0.5
min_std: 0.05
std_step: 25000
horizon_step: 25000

# Model
state_dim: 50
num_units: 256
num_layers: 4
dense_act: elu
weight_decay: 0.0
log_std: false
lstm: true
lstm_units: 128

encoder:
  # image_shape: [64, 64, 3]
  # kernel_size: [4, 4, 4, 4]
  # stride: [2, 2, 2, 2]
  image_shape: [32, 32, 3]
  kernel_size: [4, 4, 4, 2]
  stride: [2, 2, 2, 1]
  conv_dim: [32, 64, 128, 256]
  cnn_act: relu
  embed_dim: ${..num_units}
  hidden_dims: []
  dense_act: elu

decoder:
  # image_shape: [64, 64, 3]
  # kernel_size: [5, 5, 6, 6]
  # stride: [2, 2, 2, 2]
  image_shape: [32, 32, 3]
  kernel_size: [5, 5, 6, 3]
  stride: [2, 2, 2, 1]
  conv_dim: [1024, 128, 64, 32]
  cnn_act: relu
  hidden_dims:
    - ${...num_units}
    - ${...num_units}
  dense_act: elu
